version: "3.9"

services:
  meilisearch:
    image: getmeili/meilisearch:v1.1
    container_name: meilisearch
    restart: always
    ports:
      - 7700:7700
    environment:
      - MEILI_ENV=development
    volumes:
      - ${PWD}/db/meili:/meili_data 
    command: meilisearch --master-key="ThisIsMasterKey"
    networks:
      - research

  typesense:
    image: typesense/typesense:0.24.1
    container_name: typesense_search
    restart:  always
    ports:
      - "8108:8108"
    volumes:
      - ${PWD}/db/typesense:/data
    command: '--data-dir /data --api-key=ThisIsMasterKey --enable-cors'
    networks:
      - research

  postgres:
    image: postgres:alpine
    container_name: postgres-search
    restart: always
    ports:
      - 6632:5432
    environment:
      - POSTGRES_USER=user-search
      - POSTGRES_PASSWORD=user-pass
      - POSTGRES_DB=search
    volumes:
      - ${PWD}/db/postgres:/var/lib/postgresql/data
    networks:
      - research
  
  prometheus:
    container_name: prometheus
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    command: --config.file=/etc/prometheus/prometheus.yml
    ports:
      - 9091:9090
    restart: always
    depends_on:
      - cadvisor
    networks:
      - research

  grafana:
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    restart: unless-stopped
    networks:
      - research
    volumes:
      - ${PWD}/db/grafana:/var/lib/grafana

  node-exporter:
    image: prom/node-exporter:latest
    container_name: monitoring_node_exporter
    restart: unless-stopped
    expose:
      - 9100
    networks:
      - research

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.46.0
    container_name: cadvisor
    ports:
      - 8181:8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - research
    depends_on:
      - meilisearch
      - typesense
      - redis-research
  redis-research:
    image: redis:latest
    container_name: redis-research
    networks:
      - research


networks:
  research:
    driver: bridge
    

